In [29]:
pip install scikit_learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [30]:
from sklearn.datasets import load_iris
data=load_iris
iris=load_iris()

In [31]:
iris;

In [32]:
data=iris.data

In [33]:
target=iris.target

In [34]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [35]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [37]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [38]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [40]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
data.shape

(150, 4)

In [42]:
target.shape

(150,)

In [43]:
import numpy as np

In [44]:
combinacio=np.concatenate((data,target.reshape(-1,1)),axis=1)

In [45]:
combinacio

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [46]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [47]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [48]:
sepal_length=data[:,0]

In [49]:
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [50]:
sepal_length.shape

(150,)

In [51]:
sepal_length_mitjana=np.mean(sepal_length,axis=0)

In [52]:
sepal_length_mitjana

5.843333333333334

In [53]:
sepal_length_std=np.std(sepal_length,axis=0)

In [54]:
sepal_length_std

0.8253012917851409

In [55]:
petal_length=data[:,2]

In [56]:
petal_length_mitjana=np.mean(petal_length,axis=0)
petal_length_mitjana


3.7580000000000005

In [57]:
petal_length_std=np.std(petal_length,axis=0)
petal_length_std

1.759404065775303

In [58]:
petal_length_mitjana_arrodonida=np.round(petal_length_mitjana, decimals=2)
petal_length_mitjana_arrodonida

3.76

In [59]:
np.random.shuffle(data)
data_20registres=data[:20,:]
data_20registres

array([[4.8, 3.1, 1.6, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 3. , 4.8, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [4.9, 3.1, 1.5, 0.1],
       [6.1, 3. , 4.6, 1.4],
       [6.3, 2.7, 4.9, 1.8],
       [6.8, 2.8, 4.8, 1.4],
       [4.9, 3.1, 1.5, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3. , 5.2, 2.3],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 2.9, 4.2, 1.3]])

In [60]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [61]:
sepal_length

array([4.8, 5.5, 4.7, 4.6, 6.7, 6. , 6.4, 4.9, 6.1, 6.3, 6.8, 4.9, 6.5,
       6.7, 4.8, 6.7, 4.5, 6.3, 7.7, 5.7, 6.4, 4.3, 7.2, 5.2, 4.9, 5.4,
       7. , 6.3, 5.2, 4.9, 6.5, 6.5, 4.6, 6.3, 5.7, 5.5, 6.2, 6.3, 5.4,
       6.7, 4.8, 4.6, 7.9, 6.7, 5.8, 5.4, 6.4, 5. , 5.2, 4.6, 6.2, 5.8,
       5.5, 5. , 6.3, 5.1, 5.1, 7.6, 4.4, 5.1, 7.3, 6.9, 5. , 6.6, 6.4,
       5.3, 5.9, 5.4, 5.5, 5.6, 5.4, 7.2, 5.2, 4.8, 6.5, 6.4, 6.4, 6.8,
       6.8, 6.1, 6. , 5.5, 5.4, 6. , 5.1, 5.9, 6.3, 4.4, 5. , 6.2, 5. ,
       7.2, 5.5, 6. , 5.6, 5. , 5.6, 5.7, 6.1, 6.7, 5.9, 7.1, 5.8, 5.8,
       7.7, 5. , 7.7, 5. , 5. , 5.5, 5.6, 5.7, 6.1, 5.8, 5.1, 5.7, 6.7,
       6.2, 6.3, 5.6, 6.4, 6.9, 5.7, 6.9, 5.6, 5.1, 4.9, 5. , 5.1, 5.1,
       5.1, 6.5, 5.7, 6.9, 6.7, 6.6, 6.1, 6. , 6.3, 4.8, 4.9, 5.8, 5.7,
       7.4, 6. , 5.8, 4.4, 6.1, 4.7, 7.7])

In [62]:
setosa=np.arange(0,50)
versicolor=np.arange(50,100)
virginica=np.arange(100,150)

index_seleccionats=np.concatenate([np.random.choice(setosa,size=7,replace=False),np.random.choice(versicolor,size=7,replace=False), np.random.choice(virginica,size=7,replace=False) ])
valors_seleccionats=sepal_length[index_seleccionats]
especies_corresponents=np.repeat([1,2,3],7)

In [63]:
valors_seleccionats


array([6.5, 4.9, 6.7, 4.6, 7.9, 6.4, 5.7, 5. , 6.2, 5.1, 5.3, 5.5, 6.8,
       6. , 6.1, 6.5, 5.6, 5. , 6.9, 7.7, 6.9])

In [64]:
setosa_valors_seleccionats=valors_seleccionats[:7]
setosa_valors_seleccionats


array([6.5, 4.9, 6.7, 4.6, 7.9, 6.4, 5.7])

In [65]:
setosa_index_seleccionats=index_seleccionats[:7]
setosa_index_seleccionats

array([31, 24, 13, 32, 42, 20, 34])

In [66]:
index_seleccionats

array([ 31,  24,  13,  32,  42,  20,  34,  53,  50,  56,  65,  52,  77,
        80, 136, 131, 124, 107, 123, 149, 133])

In [67]:
sepal_length_mitjana_setosa=np.mean(setosa_valors_seleccionats,axis=0)
sepal_length_mitjana_setosa

6.1000000000000005

In [68]:
sepal_length_std_setosa=np.std(setosa_valors_seleccionats,axis=0)
sepal_length_std_setosa

1.0488088481701516

In [69]:
versicolor_valors_seleccionats=valors_seleccionats[7:15]
versicolor_valors_seleccionats


array([5. , 6.2, 5.1, 5.3, 5.5, 6.8, 6. , 6.1])

In [70]:
sepal_length_mitjana_versicolor=np.mean(versicolor_valors_seleccionats,axis=0)
sepal_length_mitjana_versicolor

5.75

In [71]:
virginica_valors_seleccionats=valors_seleccionats[15:]
virginica_valors_seleccionats


array([6.5, 5.6, 5. , 6.9, 7.7, 6.9])

In [72]:
sepal_length_mitjana_virginica=np.mean(virginica_valors_seleccionats,axis=0)
sepal_length_mitjana_virginica


6.433333333333334

In [73]:
especie_max_mitjana=max(sepal_length_mitjana_setosa, sepal_length_mitjana_versicolor, sepal_length_mitjana_virginica)
if especie_max_mitjana == sepal_length_mitjana_setosa:
    especie_max_mitjana = "setosa"
elif especie_max_mitjana == sepal_length_mitjana_versicolor:
    especie_max_mitjana = "versicolor"
elif especie_max_mitjana == sepal_length_mitjana_virginica:
    especie_max_mitjana = "virginica"
especie_max_mitjana

'virginica'

In [74]:
petal_length

array([1.6, 4. , 1.3, 1. , 5.7, 4.8, 5.6, 1.5, 4.6, 4.9, 4.8, 1.5, 5.5,
       5.2, 1.9, 5.7, 1.3, 4.7, 6.7, 4.2, 5.5, 1.1, 6.1, 1.5, 1.4, 1.7,
       4.7, 6. , 1.4, 1.4, 5.8, 4.6, 1.4, 4.9, 1.7, 4. , 5.4, 5.6, 4.5,
       5.8, 1.6, 1.5, 6.4, 4.4, 4. , 1.5, 5.3, 1.5, 1.5, 1.4, 4.3, 3.9,
       3.8, 1.4, 4.4, 1.4, 1.5, 6.6, 1.3, 1.9, 6.3, 5.4, 3.5, 4.4, 4.3,
       1.5, 4.2, 1.3, 1.4, 4.2, 1.5, 6. , 3.9, 1.4, 5.2, 4.5, 5.3, 5.5,
       5.9, 4.7, 4.5, 3.7, 1.7, 4. , 1.7, 4.8, 5.1, 1.4, 1.3, 4.5, 3.3,
       5.8, 4.4, 4.5, 4.1, 1.6, 3.6, 5. , 5.6, 5. , 5.1, 5.9, 4.1, 5.1,
       6.9, 1.6, 6.1, 1.6, 1.2, 1.3, 3.9, 4.2, 4.9, 5.1, 1.4, 1.5, 5.6,
       4.8, 5. , 4.9, 5.6, 5.7, 4.1, 4.9, 4.5, 1.5, 4.5, 1.4, 1.6, 1.5,
       3. , 5.1, 4.5, 5.1, 4.7, 4.6, 4. , 5. , 5.6, 1.4, 3.3, 1.2, 3.5,
       6.1, 5.1, 5.1, 1.3, 4.7, 1.6, 6.7])

In [76]:
correlacio_matriz = np.corrcoef(petal_length, sepal_length)
correlacio_matriz

array([[1.        , 0.87175378],
       [0.87175378, 1.        ]])

In [78]:
media = np.mean(valors_seleccionats)
valors_filtrats = valors_seleccionats[valors_seleccionats > media]
valors_filtrats

array([6.5, 6.7, 7.9, 6.4, 6.2, 6.8, 6.1, 6.5, 6.9, 7.7, 6.9])

In [79]:
media

6.061904761904763

In [82]:
sepal_length

array([4.8, 5.5, 4.7, 4.6, 6.7, 6. , 6.4, 4.9, 6.1, 6.3, 6.8, 4.9, 6.5,
       6.7, 4.8, 6.7, 4.5, 6.3, 7.7, 5.7, 6.4, 4.3, 7.2, 5.2, 4.9, 5.4,
       7. , 6.3, 5.2, 4.9, 6.5, 6.5, 4.6, 6.3, 5.7, 5.5, 6.2, 6.3, 5.4,
       6.7, 4.8, 4.6, 7.9, 6.7, 5.8, 5.4, 6.4, 5. , 5.2, 4.6, 6.2, 5.8,
       5.5, 5. , 6.3, 5.1, 5.1, 7.6, 4.4, 5.1, 7.3, 6.9, 5. , 6.6, 6.4,
       5.3, 5.9, 5.4, 5.5, 5.6, 5.4, 7.2, 5.2, 4.8, 6.5, 6.4, 6.4, 6.8,
       6.8, 6.1, 6. , 5.5, 5.4, 6. , 5.1, 5.9, 6.3, 4.4, 5. , 6.2, 5. ,
       7.2, 5.5, 6. , 5.6, 5. , 5.6, 5.7, 6.1, 6.7, 5.9, 7.1, 5.8, 5.8,
       7.7, 5. , 7.7, 5. , 5. , 5.5, 5.6, 5.7, 6.1, 5.8, 5.1, 5.7, 6.7,
       6.2, 6.3, 5.6, 6.4, 6.9, 5.7, 6.9, 5.6, 5.1, 4.9, 5. , 5.1, 5.1,
       5.1, 6.5, 5.7, 6.9, 6.7, 6.6, 6.1, 6. , 6.3, 4.8, 4.9, 5.8, 5.7,
       7.4, 6. , 5.8, 4.4, 6.1, 4.7, 7.7])

In [84]:
index_sepal_mes_llarg=np.argmax(sepal_length)
index_sepal_mes_llarg


42

In [85]:
sepal_length[42]

7.9